/*
  BOOKS-DATA.JS
  Generated by admin.html. You can still hand-edit this file if you'd like —
  it's just a plain array of book objects.
*/

const BOOKS = [
  {
    "id": "night-walking",
    "title": "Night Walking",
    "author": "Matthew Beaumont",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "frontImage": "images/night-walking/front.heic",
    "backImage": "images/night-walking/back.heic",
    "notes": "Pickup only, East Melbourne. Message me if you'd like it."
  },
  {
    "id": "anne-of-green-gables",
    "title": "Anne of Green Gables",
    "author": "L. M. Montgomery",
    "condition": "Good - light shelf wear",
    "available": true,
    "frontImage": "images/anne-of-green-gables/front.heic",
    "backImage": "images/anne-of-green-gables/back.heic",
    "notes": ""
  },
  {
    "id": "the-book-thief",
    "title": "The Book Thief",
    "author": "Markus Zusak",
    "condition": "Used - old library book",
    "available": true,
    "frontImage": "images/the-book-thief/front.heic",
    "backImage": "images/the-book-thief/back.heic",
    "notes": ""
  }
];

window.BOOKS = BOOKS;
