/*
  BOOKS-DATA.JS
  Generated by admin.html. You can still hand-edit this file if you'd like —
  it's just a plain array of book objects.
*/

const BOOKS = [
  {
    "id": "night-walking",
    "title": "Night Walking",
    "author": "Matthew Beaumont",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": false,
    "tags": [
      "nonfiction",
      "hardback"
    ],
    "frontImage": "images/night-walking/front.jpg",
    "backImage": "images/night-walking/back.jpg",
    "notes": "Pickup only, East Melbourne. Message me if you'd like it."
  },
  {
    "id": "anne-of-green-gables",
    "title": "Anne of Green Gables",
    "author": "L. M. Montgomery",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/anne-of-green-gables/front.jpg",
    "backImage": "images/anne-of-green-gables/back.jpg",
    "notes": ""
  },
  {
    "id": "the-book-thief",
    "title": "The Book Thief",
    "author": "Markus Zusak",
    "condition": "Used - old library book",
    "available": true,
    "tags": [
      "children",
      "historical"
    ],
    "frontImage": "images/the-book-thief/front.jpg",
    "backImage": "images/the-book-thief/back.jpg",
    "notes": ""
  },
  {
    "id": "love-virtue",
    "title": "Love & Virtue",
    "author": "Diana Reid",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/love-virtue/front.jpg",
    "backImage": "images/love-virtue/back.jpg",
    "notes": ""
  },
  {
    "id": "the-assault",
    "title": "The Assault",
    "author": "Harry Mulisch",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "fiction",
      "literature",
      "historical"
    ],
    "frontImage": "images/the-assault/front.jpg",
    "backImage": "images/the-assault/back.jpg",
    "notes": ""
  },
  {
    "id": "the-bread-the-devil-knead",
    "title": "The Bread the Devil Knead",
    "author": "Lisa Allen-Agostini",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/the-bread-the-devil-knead/front.jpg",
    "backImage": "images/the-bread-the-devil-knead/back.jpg",
    "notes": ""
  },
  {
    "id": "my-own-words",
    "title": "My Own Words",
    "author": "Ruth Bader Ginsburg",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "nonfiction",
      "biography",
      "law"
    ],
    "frontImage": "images/my-own-words/front.jpg",
    "backImage": "images/my-own-words/back.jpg",
    "notes": ""
  },
  {
    "id": "the-better-angels-of-our-nature",
    "title": "The Better Angels of Our Nature",
    "author": "Steven Pinker",
    "condition": "Used - Old Library Book",
    "available": true,
    "tags": [
      "nonfiction",
      "philosophy"
    ],
    "frontImage": "images/the-better-angels-of-our-nature/front.jpg",
    "backImage": "images/the-better-angels-of-our-nature/back.jpg",
    "notes": ""
  },
  {
    "id": "alias-grace",
    "title": "Alias Grace",
    "author": "Margaret Atwood",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fiction",
      "literature"
    ],
    "frontImage": "images/alias-grace/front.jpg",
    "backImage": "images/alias-grace/back.jpg",
    "notes": ""
  },
  {
    "id": "flesh",
    "title": "Flesh",
    "author": "David Szalay",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/flesh/front.jpg",
    "backImage": "images/flesh/back.jpg",
    "notes": ""
  },
  {
    "id": "conspiracy-nation",
    "title": "Conspiracy Nation",
    "author": "Ariel Bogle and Cam Wilson",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "nonfiction"
    ],
    "frontImage": "images/conspiracy-nation/front.jpg",
    "backImage": "images/conspiracy-nation/back.jpg",
    "notes": ""
  },
  {
    "id": "percy-jackson",
    "title": "Percy Jackson Heroes of Olympus Son of Nepture",
    "author": "Rick Riordan",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/percy-jackson/front.jpg",
    "backImage": "images/percy-jackson/back.jpg",
    "notes": ""
  },
  {
    "id": "percy-jackson-heroes-of-olympus-the-mark-of-athena",
    "title": "Percy Jackson Heroes of Olympus The Mark of Athena",
    "author": "Rick Riordan",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/percy-jackson-heroes-of-olympus-the-mark-of-athena/front.jpg",
    "backImage": "images/percy-jackson-heroes-of-olympus-the-mark-of-athena/back.jpg",
    "notes": ""
  },
  {
    "id": "the-great-hunt-wheel-of-time",
    "title": "The Great Hunt (Wheel of Time)",
    "author": "Robert Jordan",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/the-great-hunt-wheel-of-time/front.jpg",
    "backImage": "images/the-great-hunt-wheel-of-time/back.jpg",
    "notes": ""
  },
  {
    "id": "the-dragon-reborn-the-wheel-of-time",
    "title": "The Dragon Reborn (The Wheel of Time)",
    "author": "Robert Jordan",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/the-dragon-reborn-the-wheel-of-time/front.jpg",
    "backImage": "images/the-dragon-reborn-the-wheel-of-time/back.jpg",
    "notes": ""
  },
  {
    "id": "ivy-bean",
    "title": "Ivy + Bean (Ivy + Bean 1)",
    "author": "Annie Barrows",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/ivy-bean/front.jpg",
    "backImage": "images/ivy-bean/back.jpg",
    "notes": ""
  },
  {
    "id": "ivy-bean-and-the-ghost-that-had-to-go-ivy-bean-2",
    "title": "Ivy + Bean And The Ghost That Had To Go (Ivy + Bean 2)",
    "author": "Annie Burrows",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/ivy-bean-and-the-ghost-that-had-to-go-ivy-bean-2/front.jpg",
    "backImage": "images/ivy-bean-and-the-ghost-that-had-to-go-ivy-bean-2/back.jpg",
    "notes": ""
  },
  {
    "id": "ivy-bean-break-the-fossil-record",
    "title": "Ivy + Bean Break the Fossil Record (Ivy + Bean 3)",
    "author": "Annie Burrows",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/ivy-bean-break-the-fossil-record/front.jpg",
    "backImage": "images/ivy-bean-break-the-fossil-record/back.jpg",
    "notes": ""
  },
  {
    "id": "the-red-queen",
    "title": "The Red Queen",
    "author": "Philippa Gregory",
    "condition": "Used",
    "available": true,
    "tags": [
      "historical",
      "fiction"
    ],
    "frontImage": "images/the-red-queen/front.jpg",
    "backImage": "images/the-red-queen/back.jpg",
    "notes": ""
  },
  {
    "id": "what-happens-now",
    "title": "What Happens Now?",
    "author": "Sophia Money-Coutts",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "romance",
      "fiction"
    ],
    "frontImage": "images/what-happens-now/front.jpg",
    "backImage": "images/what-happens-now/back.jpg",
    "notes": ""
  },
  {
    "id": "disquiet-please",
    "title": "Disquiet Please",
    "author": "The New Yorker",
    "condition": "Used - old library book",
    "available": true,
    "tags": [
      "short stories"
    ],
    "frontImage": "images/disquiet-please/front.jpg",
    "backImage": "images/disquiet-please/back.jpg",
    "notes": ""
  },
  {
    "id": "leprechaun-tales",
    "title": "Leprechaun Tales",
    "author": "N/A",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "children",
      "fairytales"
    ],
    "frontImage": "images/leprechaun-tales/front.jpg",
    "backImage": "images/leprechaun-tales/back.jpg",
    "notes": ""
  },
  {
    "id": "irish-fairies",
    "title": "Irish Fairies",
    "author": "Appletree Pocket Guides",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children",
      "fairytales"
    ],
    "frontImage": "images/irish-fairies/front.jpg",
    "backImage": "images/irish-fairies/back.jpg",
    "notes": ""
  },
  {
    "id": "the-outsider",
    "title": "The Outsider",
    "author": "Camus",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "literature",
      "fiction"
    ],
    "frontImage": "images/the-outsider/front.jpg",
    "backImage": "images/the-outsider/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-philosopher-s-stone-harry-potter-1",
    "title": "Harry Potter and the Philosopher's Stone (Harry Potter 1)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1/front.jpg",
    "backImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-chamber-of-secrets-harry-potter-2",
    "title": "Harry Potter and the Chamber of Secrets (Harry Potter 2)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/harry-potter-and-the-chamber-of-secrets-harry-potter-2/front.jpg",
    "backImage": "images/harry-potter-and-the-chamber-of-secrets-harry-potter-2/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-prisoner-of-azkaban-harry-potter-3",
    "title": "Harry Potter and the Prisoner of Azkaban (Harry Potter 3)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-prisoner-of-azkaban-harry-potter-3/front.jpg",
    "backImage": "images/harry-potter-and-the-prisoner-of-azkaban-harry-potter-3/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-philosopher-s-stone-harry-potter-1-2",
    "title": "Harry Potter and the Philosopher's Stone (Harry Potter 1)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1-2/front.jpg",
    "backImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1-2/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-goblet-of-fire-harry-potter-4",
    "title": "Harry Potter and the Goblet of Fire (Harry Potter 4)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-goblet-of-fire-harry-potter-4/front.jpg",
    "backImage": "images/harry-potter-and-the-goblet-of-fire-harry-potter-4/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-order-of-the-phoenix-harry-potter-5",
    "title": "Harry Potter and the Order of the Phoenix (Harry Potter 5)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-order-of-the-phoenix-harry-potter-5/front.jpg",
    "backImage": "images/harry-potter-and-the-order-of-the-phoenix-harry-potter-5/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-half-blood-prince-book-6",
    "title": "Harry Potter and the Half-Blood Prince (Harry Potter 6)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-half-blood-prince-book-6/front.jpg",
    "backImage": "images/harry-potter-and-the-half-blood-prince-book-6/back.jpg",
    "notes": ""
  },
  {
    "id": "emily-s-quest",
    "title": "Emily's Quest",
    "author": "L.M. Montgomery",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/emily-s-quest/front.jpg",
    "backImage": "images/emily-s-quest/back.jpg",
    "notes": ""
  },
  {
    "id": "shadow-s-edge",
    "title": "Shadow's Edge (The Night Angel Trilogy 2)",
    "author": "Brent Weeks",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/shadow-s-edge/front.jpg",
    "backImage": "images/shadow-s-edge/back.jpg",
    "notes": ""
  },
  {
    "id": "wallflower-wager",
    "title": "Wallflower Wager",
    "author": "Tessa Dare",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "romance",
      "fiction"
    ],
    "frontImage": "images/wallflower-wager/front.jpg",
    "backImage": "images/wallflower-wager/back.jpg",
    "notes": ""
  },
  {
    "id": "the-invention-of-wings",
    "title": "The Invention of Wings",
    "author": "Sue Monk Kidd",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "historical",
      "contemporary literature",
      "fiction"
    ],
    "frontImage": "images/the-invention-of-wings/front.jpg",
    "backImage": "images/the-invention-of-wings/back.jpg",
    "notes": ""
  },
  {
    "id": "the-book-of-goose",
    "title": "The Book of Goose",
    "author": "Yiyun Li",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/the-book-of-goose/front.jpg",
    "backImage": "images/the-book-of-goose/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-dealthy-hallows-book-7",
    "title": "Harry Potter and the Dealthy Hallows (Book 7)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-dealthy-hallows-book-7/front.jpg",
    "backImage": "images/harry-potter-and-the-dealthy-hallows-book-7/back.jpg",
    "notes": ""
  },
  {
    "id": "the-secret-barrister",
    "title": "The Secret Barrister",
    "author": "N/A",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "nonfiction",
      "law"
    ],
    "frontImage": "images/the-secret-barrister/front.jpg",
    "backImage": "images/the-secret-barrister/back.jpg",
    "notes": ""
  },
  {
    "id": "law-s-strangest-cases",
    "title": "Law's Strangest Cases",
    "author": "Peter Seddon",
    "condition": "Very Good — light shelf wear",
    "available": true,
    "tags": [
      "law",
      "nonfiction",
      "hardback"
    ],
    "frontImage": "images/law-s-strangest-cases/front.jpg",
    "backImage": "images/law-s-strangest-cases/back.jpg",
    "notes": ""
  },
  {
    "id": "the-odd-woman-and-the-city",
    "title": "The Odd Woman and the City",
    "author": "Vivian Gornick",
    "condition": "Used - old library book",
    "available": true,
    "tags": [
      "nonfiction",
      "biography"
    ],
    "frontImage": "images/the-odd-woman-and-the-city/front.jpg",
    "backImage": "images/the-odd-woman-and-the-city/back.jpg",
    "notes": ""
  },
  {
    "id": "witches-abroad-discworld",
    "title": "Witches Abroad (Discworld)",
    "author": "Terry Pratchett",
    "condition": "Used - library book",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/witches-abroad-discworld/front.jpg",
    "backImage": "images/witches-abroad-discworld/back.jpg",
    "notes": ""
  },
  {
    "id": "cats",
    "title": "Cats",
    "author": "N/A",
    "condition": "Very Good — light shelf wear",
    "available": true,
    "tags": [
      "nonfiction",
      "animals",
      "children",
      "hardback"
    ],
    "frontImage": "images/cats/front.jpg",
    "backImage": "images/cats/back.jpg",
    "notes": ""
  },
  {
    "id": "krondor-tear-of-the-gods",
    "title": "Krondor: Tear of the Gods",
    "author": "Raymond E. Feist",
    "condition": "Good - shelf wear",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/krondor-tear-of-the-gods/front.jpg",
    "backImage": "images/krondor-tear-of-the-gods/back.jpg",
    "notes": ""
  },
  {
    "id": "constance-the-tragic-and-scandalous-life-of-mrs-oscar-wilde",
    "title": "Constance The Tragic and Scandalous Life of Mrs Oscar Wilde",
    "author": "Franny Moyle",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "nonfiction",
      "biography"
    ],
    "frontImage": "images/constance-the-tragic-and-scandalous-life-of-mrs-oscar-wilde/front.jpg",
    "backImage": "images/constance-the-tragic-and-scandalous-life-of-mrs-oscar-wilde/back.jpg",
    "notes": ""
  },
  {
    "id": "station-eleven",
    "title": "Station Eleven",
    "author": "Emily St John Mandel",
    "condition": "Very Good — light shelf wear",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature",
      "dystopia"
    ],
    "frontImage": "images/station-eleven/front.jpg",
    "backImage": "images/station-eleven/back.jpg",
    "notes": ""
  },
  {
    "id": "utterly-me-clarice-bean",
    "title": "Utterly Me, Clarice Bean",
    "author": "Lauren Child",
    "condition": "Used",
    "available": true,
    "tags": [
      "Children"
    ],
    "frontImage": "images/utterly-me-clarice-bean/front.jpg",
    "backImage": "images/utterly-me-clarice-bean/back.jpg",
    "notes": ""
  },
  {
    "id": "don-t-look-now-clarice-bean",
    "title": "Don't Look Now (Clarice Bean)",
    "author": "Lauren Child",
    "condition": "Good",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/don-t-look-now-clarice-bean/front.jpg",
    "backImage": "images/don-t-look-now-clarice-bean/back.jpg",
    "notes": ""
  },
  {
    "id": "clarice-bean-spells-trouble",
    "title": "Clarice Bean Spells Trouble",
    "author": "Lauren Child",
    "condition": "Good",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/clarice-bean-spells-trouble/front.jpg",
    "backImage": "images/clarice-bean-spells-trouble/back.jpg",
    "notes": ""
  },
  {
    "id": "sophie-s-misfortunes-the-fleurville-trilogy",
    "title": "Sophie's Misfortunes (The Fleurville Trilogy 1)",
    "author": "Countess de Segur",
    "condition": "Good - shelf wear",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/sophie-s-misfortunes-the-fleurville-trilogy/front.jpg",
    "backImage": "images/sophie-s-misfortunes-the-fleurville-trilogy/back.jpg",
    "notes": ""
  },
  {
    "id": "camille-and-madeleine",
    "title": "Camille and Madeleine (The Fleurville Trilogy 2)",
    "author": "Countess de Segur",
    "condition": "Good - shelf wear",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/camille-and-madeleine/front.jpg",
    "backImage": "images/camille-and-madeleine/back.jpg",
    "notes": ""
  },
  {
    "id": "the-diary-of-a-young-girl-anne-frank",
    "title": "The Diary of a Young Girl (Anne Frank)",
    "author": "Anne Frank",
    "condition": "Good",
    "available": true,
    "tags": [
      "children",
      "historical"
    ],
    "frontImage": "images/the-diary-of-a-young-girl-anne-frank/front.jpg",
    "backImage": "images/the-diary-of-a-young-girl-anne-frank/back.jpg",
    "notes": ""
  },
  {
    "id": "the-children-of-green-knowe",
    "title": "The Children of Green Knowe",
    "author": "Lucy M. Boston",
    "condition": "Good - small piece of writing on first page",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/the-children-of-green-knowe/front.jpg",
    "backImage": "images/the-children-of-green-knowe/back.jpg",
    "notes": ""
  },
  {
    "id": "the-wizard-of-oz",
    "title": "The Wizard of Oz",
    "author": "L. Frank Baum",
    "condition": "Good",
    "available": true,
    "tags": [
      "children",
      "literature"
    ],
    "frontImage": "images/the-wizard-of-oz/front.jpg",
    "backImage": "images/the-wizard-of-oz/back.jpg",
    "notes": ""
  },
  {
    "id": "mort-discworld",
    "title": "Mort (Discworld)",
    "author": "Terry Pratchett",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/mort-discworld/front.jpg",
    "backImage": "images/mort-discworld/back.jpg",
    "notes": ""
  },
  {
    "id": "magician-s-nephew-narnia-1",
    "title": "Magician's Nephew (Narnia 1)",
    "author": "C.S. Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/magician-s-nephew-narnia-1/front.jpg",
    "backImage": "images/magician-s-nephew-narnia-1/back.jpg",
    "notes": ""
  },
  {
    "id": "the-lion-the-witch-and-the-wardrobe",
    "title": "The Lion, the Witch and the Wardrobe (Narnia 2)",
    "author": "C.S. Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/the-lion-the-witch-and-the-wardrobe/front.jpg",
    "backImage": "images/the-lion-the-witch-and-the-wardrobe/back.jpg",
    "notes": ""
  },
  {
    "id": "the-horse-and-his-boy-narnia-2",
    "title": "The Horse and His Boy (Narnia 3)",
    "author": "C.S. Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/the-horse-and-his-boy-narnia-2/front.jpg",
    "backImage": "images/the-horse-and-his-boy-narnia-2/back.jpg",
    "notes": ""
  },
  {
    "id": "prince-caspian-narnia-4",
    "title": "Prince Caspian (Narnia 4)",
    "author": "C.S. Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/prince-caspian-narnia-4/front.jpg",
    "backImage": "images/prince-caspian-narnia-4/back.jpg",
    "notes": ""
  },
  {
    "id": "the-voyage-of-the-dawn-trader-narnia-5",
    "title": "The Voyage of the Dawn Trader (Narnia 5)",
    "author": "C.S. Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-voyage-of-the-dawn-trader-narnia-5/front.jpg",
    "backImage": "images/the-voyage-of-the-dawn-trader-narnia-5/back.jpg",
    "notes": ""
  },
  {
    "id": "the-silver-chair-narnia-6",
    "title": "The Silver Chair (Narnia 6)",
    "author": "C.S. Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-silver-chair-narnia-6/front.jpg",
    "backImage": "images/the-silver-chair-narnia-6/back.jpg",
    "notes": ""
  },
  {
    "id": "the-last-battle-narnia-7",
    "title": "The Last Battle (Narnia 7)",
    "author": "C.S. Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-last-battle-narnia-7/front.jpg",
    "backImage": "images/the-last-battle-narnia-7/back.jpg",
    "notes": ""
  },
  {
    "id": "silent-night-and-other-christmas-carols",
    "title": "Silent Night and Other Christmas Carols",
    "author": "N/A",
    "condition": "Good - beautiful book but with some tears",
    "available": true,
    "tags": [
      "children",
      "fairytales"
    ],
    "frontImage": "images/silent-night-and-other-christmas-carols/front.jpg",
    "backImage": "images/silent-night-and-other-christmas-carols/back.jpg",
    "notes": ""
  },
  {
    "id": "flora-ulysses",
    "title": "Flora & Ulysses",
    "author": "Kate DiCamillo",
    "condition": "Very good",
    "available": true,
    "tags": [
      "children",
      "hardback"
    ],
    "frontImage": "images/flora-ulysses/front.jpg",
    "backImage": "images/flora-ulysses/back.jpg",
    "notes": ""
  },
  {
    "id": "losing-it",
    "title": "Losing It",
    "author": "Ranjit Bolt",
    "condition": "Used - old library book",
    "available": true,
    "tags": [
      "fiction",
      "poetry"
    ],
    "frontImage": "images/losing-it/front.jpg",
    "backImage": "images/losing-it/back.jpg",
    "notes": ""
  },
  {
    "id": "the-key-to-rondo-rondo-1",
    "title": "The Key to Rondo (Rondo 1)",
    "author": "Emily Rodda",
    "condition": "Good",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/the-key-to-rondo-rondo-1/front.jpg",
    "backImage": "images/the-key-to-rondo-rondo-1/back.jpg",
    "notes": ""
  },
  {
    "id": "the-wizard-of-rondo-rondo-2",
    "title": "The Wizard of Rondo (Rondo 2)",
    "author": "Emily Rodda",
    "condition": "Good",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/the-wizard-of-rondo-rondo-2/front.jpg",
    "backImage": "images/the-wizard-of-rondo-rondo-2/back.jpg",
    "notes": ""
  },
  {
    "id": "science-without-the-boring-bits",
    "title": "Science without the Boring Bits",
    "author": "Ian Crofton",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "hardback",
      "children",
      "nonfiction",
      "science"
    ],
    "frontImage": "images/science-without-the-boring-bits/front.jpg",
    "backImage": "images/science-without-the-boring-bits/back.jpg",
    "notes": ""
  },
  {
    "id": "aunt-dan-and-lemon",
    "title": "Aunt Dan and Lemon",
    "author": "Wallace Shawn",
    "condition": "excellent",
    "available": true,
    "tags": [
      "fiction",
      "play"
    ],
    "frontImage": "images/aunt-dan-and-lemon/front.jpg",
    "backImage": "images/aunt-dan-and-lemon/back.jpg",
    "notes": ""
  },
  {
    "id": "the-way-of-kings-stormlight-archive-1",
    "title": "The Way of Kings (Stormlight Archive 1)",
    "author": "Brandon Sanderson",
    "condition": "Very Good — light shelf wear",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/the-way-of-kings-stormlight-archive-1/front.jpg",
    "backImage": "images/the-way-of-kings-stormlight-archive-1/back.jpg",
    "notes": ""
  },
  {
    "id": "words-of-radiance-stormlight-archive-2",
    "title": "Words of Radiance (Stormlight Archive 2)",
    "author": "Brandon Sanderson",
    "condition": "Very good - light shelf wear",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/words-of-radiance-stormlight-archive-2/front.jpg",
    "backImage": "images/words-of-radiance-stormlight-archive-2/back.jpg",
    "notes": ""
  },
  {
    "id": "othello",
    "title": "Othello",
    "author": "William Shakespeare",
    "condition": "used - highlighter inside",
    "available": true,
    "tags": [
      "literature",
      "play"
    ],
    "frontImage": "images/othello/front.jpg",
    "backImage": "images/othello/back.jpg",
    "notes": ""
  },
  {
    "id": "australian-concise-oxford-dictionary",
    "title": "Australian Concise Oxford Dictionary",
    "author": "N/A",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "nonfiction",
      "reference"
    ],
    "frontImage": "images/australian-concise-oxford-dictionary/front.jpg",
    "backImage": "images/australian-concise-oxford-dictionary/back.jpg",
    "notes": ""
  },
  {
    "id": "rhythm-of-nature",
    "title": "Rhythm of Nature",
    "author": "Heather Gall",
    "condition": "Very good",
    "available": true,
    "tags": [
      "poetry",
      "signed by author"
    ],
    "frontImage": "images/rhythm-of-nature/front.jpg",
    "backImage": "images/rhythm-of-nature/back.jpg",
    "notes": ""
  },
  {
    "id": "the-little-box-of-economics",
    "title": "The Little Box of Economics",
    "author": "Grep Ip",
    "condition": "Used - old library book",
    "available": true,
    "tags": [
      "nonfiction",
      "hardback"
    ],
    "frontImage": "images/the-little-box-of-economics/front.jpg",
    "backImage": "images/the-little-box-of-economics/back.jpg",
    "notes": ""
  },
  {
    "id": "memories",
    "title": "Memories",
    "author": "Lang Leav",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "poetry",
      "hardback"
    ],
    "frontImage": "images/memories/front.jpg",
    "backImage": "images/memories/back.jpg",
    "notes": ""
  },
  {
    "id": "the-lost-spells",
    "title": "The Lost Spells",
    "author": "Robert MacFarlane and Jackie Morris",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "poetry",
      "hardback"
    ],
    "frontImage": "images/the-lost-spells/front.jpg",
    "backImage": "images/the-lost-spells/back.jpg",
    "notes": ""
  },
  {
    "id": "magical-negro",
    "title": "Magical Negro",
    "author": "Morgan Parker",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "poetry"
    ],
    "frontImage": "images/magical-negro/front.jpg",
    "backImage": "images/magical-negro/back.jpg",
    "notes": ""
  },
  {
    "id": "10-000-years-of-art",
    "title": "10,000 Years of Art",
    "author": "Phaidon",
    "condition": "Good - shelf wear",
    "available": true,
    "tags": [
      "nonfiction",
      "reference"
    ],
    "frontImage": "images/10-000-years-of-art/front.jpg",
    "backImage": "images/10-000-years-of-art/back.jpg",
    "notes": ""
  },
  {
    "id": "toutes-les-intelligences-du-monde",
    "title": "Toutes les intelligences du monde",
    "author": "James Bridle",
    "condition": "Very good",
    "available": true,
    "tags": [
      "nonfiction",
      "french"
    ],
    "frontImage": "images/toutes-les-intelligences-du-monde/front.jpg",
    "backImage": "images/toutes-les-intelligences-du-monde/back.jpg",
    "notes": "This is in French"
  },
  {
    "id": "call-us-what-we-carry",
    "title": "Call Us What We Carry",
    "author": "Amanda Gorman",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "hardback",
      "poetry"
    ],
    "frontImage": "images/call-us-what-we-carry/front.jpg",
    "backImage": "images/call-us-what-we-carry/back.jpg",
    "notes": ""
  },
  {
    "id": "paper-boat",
    "title": "Paper Boat",
    "author": "Margaret Atwood",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "poetry",
      "hardback"
    ],
    "frontImage": "images/paper-boat/front.jpg",
    "backImage": "images/paper-boat/back.jpg",
    "notes": ""
  },
  {
    "id": "no-ordinary-genius",
    "title": "No Ordinary Genius",
    "author": "Richard Feynman",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "nonfiction",
      "science"
    ],
    "frontImage": "images/no-ordinary-genius/front.jpg",
    "backImage": "images/no-ordinary-genius/back.jpg",
    "notes": ""
  },
  {
    "id": "the-folk-of-the-faraway-tree",
    "title": "The Folk of the Faraway Tree",
    "author": "Enid Blyton",
    "condition": "Good - shelf wear",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-folk-of-the-faraway-tree/front.jpg",
    "backImage": "images/the-folk-of-the-faraway-tree/back.jpg",
    "notes": ""
  },
  {
    "id": "the-magic-faraway-tree",
    "title": "The Magic Faraway Tree",
    "author": "Enid Blyton",
    "condition": "Good - shelf wear",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-magic-faraway-tree/front.jpg",
    "backImage": "images/the-magic-faraway-tree/back.jpg",
    "notes": ""
  },
  {
    "id": "the-magical-adventures-of-the-wishing-chair",
    "title": "The Magical Adventures of the Wishing Chair",
    "author": "Enid Blyton",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-magical-adventures-of-the-wishing-chair/front.jpg",
    "backImage": "images/the-magical-adventures-of-the-wishing-chair/back.jpg",
    "notes": ""
  },
  {
    "id": "the-good-people",
    "title": "The Good People",
    "author": "Hannah Kent",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/the-good-people/front.jpg",
    "backImage": "images/the-good-people/back.jpg",
    "notes": ""
  },
  {
    "id": "the-way-of-shadows-the-night-angel-trilogy-1",
    "title": "The Way of Shadows (The Night Angel Trilogy 1)",
    "author": "Brent Weeks",
    "condition": "Very Good — light shelf wear",
    "available": true,
    "tags": [
      "fantasy"
    ],
    "frontImage": "images/the-way-of-shadows-the-night-angel-trilogy-1/front.jpg",
    "backImage": "images/the-way-of-shadows-the-night-angel-trilogy-1/back.jpg",
    "notes": ""
  },
  {
    "id": "inkheart",
    "title": "Inkheart",
    "author": "Cornelia Funke",
    "condition": "good - shelf wear",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/inkheart/front.jpg",
    "backImage": "images/inkheart/back.jpg",
    "notes": ""
  },
  {
    "id": "the-little-princess",
    "title": "The Little Princess",
    "author": "Frances Hodgson Burnett",
    "condition": "Good - shelf wear",
    "available": true,
    "tags": [
      "children",
      "literature"
    ],
    "frontImage": "images/the-little-princess/front.jpg",
    "backImage": "images/the-little-princess/back.jpg",
    "notes": ""
  },
  {
    "id": "a-wrinkle-in-time",
    "title": "A Wrinkle in Time",
    "author": "Madeleine L'Engle",
    "condition": "Good - some writing on first page",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/a-wrinkle-in-time/front.jpg",
    "backImage": "images/a-wrinkle-in-time/back.jpg",
    "notes": ""
  },
  {
    "id": "the-road",
    "title": "The Road",
    "author": "Cormac McCarthy",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "literature",
      "fiction",
      "dystopia"
    ],
    "frontImage": "images/the-road/front.jpg",
    "backImage": "images/the-road/back.jpg",
    "notes": ""
  },
  {
    "id": "rumpelstiltskin",
    "title": "Rumpelstiltskin",
    "author": "Paul O. Zelinsky",
    "condition": "Good - writing on front page",
    "available": true,
    "tags": [
      "children",
      "fairytales"
    ],
    "frontImage": "images/rumpelstiltskin/front.jpg",
    "backImage": "images/rumpelstiltskin/back.jpg",
    "notes": ""
  },
  {
    "id": "nineteen-eighty-four",
    "title": "Nineteen Eighty-Four",
    "author": "George Orwell",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "dystopia",
      "fiction",
      "literature"
    ],
    "frontImage": "images/nineteen-eighty-four/front.jpg",
    "backImage": "images/nineteen-eighty-four/back.jpg",
    "notes": ""
  },
  {
    "id": "the-wife-of-martin-guerre",
    "title": "The Wife of Martin Guerre",
    "author": "Janet Lewis",
    "condition": "Good",
    "available": true,
    "tags": [
      "literature",
      "fiction"
    ],
    "frontImage": "images/the-wife-of-martin-guerre/front.jpg",
    "backImage": "images/the-wife-of-martin-guerre/back.jpg",
    "notes": ""
  },
  {
    "id": "pride-and-prejudice",
    "title": "Pride and Prejudice",
    "author": "Jane Austen",
    "condition": "Good",
    "available": true,
    "tags": [
      "literature",
      "fiction",
      "romance"
    ],
    "frontImage": "images/pride-and-prejudice/front.jpg",
    "backImage": "images/pride-and-prejudice/back.jpg",
    "notes": ""
  },
  {
    "id": "my-cousin-rachel",
    "title": "My Cousin Rachel",
    "author": "Daphne Du Maurier",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "literature",
      "fiction",
      "romance"
    ],
    "frontImage": "images/my-cousin-rachel/front.jpg",
    "backImage": "images/my-cousin-rachel/back.jpg",
    "notes": ""
  },
  {
    "id": "tao-te-ching",
    "title": "Tao Te Ching",
    "author": "Lao Tzu",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "literature",
      "philosophy"
    ],
    "frontImage": "images/tao-te-ching/front.jpg",
    "backImage": "images/tao-te-ching/back.jpg",
    "notes": ""
  },
  {
    "id": "selected-diaries",
    "title": "Selected Diaries",
    "author": "Virginia Woolf",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "literature",
      "nonfiction",
      "biography"
    ],
    "frontImage": "images/selected-diaries/front.jpg",
    "backImage": "images/selected-diaries/back.jpg",
    "notes": ""
  },
  {
    "id": "my-grammar-and-i",
    "title": "My Grammar and I",
    "author": "Caroline Taggart and J.A. Wines",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "nonfiction",
      "reference",
      "hardback"
    ],
    "frontImage": "images/my-grammar-and-i/front.jpg",
    "backImage": "images/my-grammar-and-i/back.jpg",
    "notes": ""
  },
  {
    "id": "quid-pro-quo",
    "title": "Quid Pro Quo",
    "author": "Peter Jones",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "nonfiction",
      "hardback",
      "reference",
      "latin"
    ],
    "frontImage": "images/quid-pro-quo/front.jpg",
    "backImage": "images/quid-pro-quo/back.jpg",
    "notes": ""
  },
  {
    "id": "aeneid-book-xii",
    "title": "Aeneid Book XII",
    "author": "Virgil",
    "condition": "Good",
    "available": true,
    "tags": [
      "literature",
      "latin",
      "poetry"
    ],
    "frontImage": "images/aeneid-book-xii/front.jpg",
    "backImage": "images/aeneid-book-xii/back.jpg",
    "notes": "This does not have a translation and is just in Latin"
  },
  {
    "id": "deltora-quest-the-complete-collection",
    "title": "Deltora Quest: The Complete Collection",
    "author": "Emily Rodda",
    "condition": "Good",
    "available": true,
    "tags": [
      "fantasy",
      "children",
      "hardback"
    ],
    "frontImage": "images/deltora-quest-the-complete-collection/front.jpg",
    "backImage": "images/deltora-quest-the-complete-collection/back.jpg",
    "notes": ""
  },
  {
    "id": "deltora-quest-2-the-complete-collection",
    "title": "Deltora Quest 2: The Complete Collection",
    "author": "Emily Rodda",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fantasy",
      "children",
      "hardback"
    ],
    "frontImage": "images/deltora-quest-2-the-complete-collection/front.jpg",
    "backImage": "images/deltora-quest-2-the-complete-collection/back.jpg",
    "notes": ""
  },
  {
    "id": "deltora-quest-3-the-complete-collection",
    "title": "Deltora Quest 3: The Complete Collection",
    "author": "Emily Rodda",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fantasy",
      "children",
      "hardback"
    ],
    "frontImage": "images/deltora-quest-3-the-complete-collection/front.jpg",
    "backImage": "images/deltora-quest-3-the-complete-collection/back.jpg",
    "notes": ""
  },
  {
    "id": "the-deltora-book-of-monsters",
    "title": "The Deltora Book of Monsters",
    "author": "Emily Rodda",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fantasy",
      "children",
      "reference"
    ],
    "frontImage": "images/the-deltora-book-of-monsters/front.jpg",
    "backImage": "images/the-deltora-book-of-monsters/back.jpg",
    "notes": ""
  },
  {
    "id": "secrets-of-deltora",
    "title": "Secrets of Deltora",
    "author": "Emily Rodda",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fantasy",
      "children",
      "reference",
      "hardback"
    ],
    "frontImage": "images/secrets-of-deltora/front.jpg",
    "backImage": "images/secrets-of-deltora/back.jpg",
    "notes": ""
  },
  {
    "id": "the-big-book-of-tashi",
    "title": "The Big Book of Tashi",
    "author": "Anna & Barbara Fienberg and Kim Gamble",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-big-book-of-tashi/front.jpg",
    "backImage": "images/the-big-book-of-tashi/back.jpg",
    "notes": ""
  },
  {
    "id": "the-2nd-big-book-of-tashi",
    "title": "The 2nd Big Book of Tashi",
    "author": "Anna & Barbara Fienberg and Kim Gamble",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/the-2nd-big-book-of-tashi/front.jpg",
    "backImage": "images/the-2nd-big-book-of-tashi/back.jpg",
    "notes": ""
  },
  {
    "id": "tashi-and-the-mixed-up-monster",
    "title": "Tashi and the Mixed-up Monster",
    "author": "Anna & Barbara Fienberg and Kim Gamble",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/tashi-and-the-mixed-up-monster/front.jpg",
    "backImage": "images/tashi-and-the-mixed-up-monster/back.jpg",
    "notes": ""
  }
];

window.BOOKS = BOOKS;
