/*
  BOOKS-DATA.JS
  Generated by admin.html. You can still hand-edit this file if you'd like —
  it's just a plain array of book objects.
*/

const BOOKS = [
  {
    "id": "night-walking",
    "title": "Night Walking",
    "author": "Matthew Beaumont",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "nonfiction"
    ],
    "frontImage": "images/night-walking/front.jpg",
    "backImage": "images/night-walking/back.jpg",
    "notes": "Pickup only, East Melbourne. Message me if you'd like it."
  },
  {
    "id": "anne-of-green-gables",
    "title": "Anne of Green Gables",
    "author": "L. M. Montgomery",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/anne-of-green-gables/front.jpg",
    "backImage": "images/anne-of-green-gables/back.jpg",
    "notes": ""
  },
  {
    "id": "the-book-thief",
    "title": "The Book Thief",
    "author": "Markus Zusak",
    "condition": "Used - old library book",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/the-book-thief/front.jpg",
    "backImage": "images/the-book-thief/back.jpg",
    "notes": ""
  },
  {
    "id": "love-virtue",
    "title": "Love & Virtue",
    "author": "Diana Reid",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/love-virtue/front.jpg",
    "backImage": "images/love-virtue/back.jpg",
    "notes": ""
  },
  {
    "id": "the-assault",
    "title": "The Assault",
    "author": "Harry Mulisch",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "fiction",
      "literature"
    ],
    "frontImage": "images/the-assault/front.jpg",
    "backImage": "images/the-assault/back.jpg",
    "notes": ""
  },
  {
    "id": "the-bread-the-devil-knead",
    "title": "The Bread the Devil Knead",
    "author": "Lisa Allen-Agostini",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/the-bread-the-devil-knead/front.jpg",
    "backImage": "images/the-bread-the-devil-knead/back.jpg",
    "notes": ""
  },
  {
    "id": "my-own-words",
    "title": "My Own Words",
    "author": "Ruth Bader Ginsburg",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "nonfiction",
      "biography"
    ],
    "frontImage": "images/my-own-words/front.jpg",
    "backImage": "images/my-own-words/back.jpg",
    "notes": ""
  },
  {
    "id": "the-better-angels-of-our-nature",
    "title": "The Better Angels of Our Nature",
    "author": "Steven Pinker",
    "condition": "Used - Old Library Book",
    "available": true,
    "tags": [
      "nonfiction",
      "biography"
    ],
    "frontImage": "images/the-better-angels-of-our-nature/front.jpg",
    "backImage": "images/the-better-angels-of-our-nature/back.jpg",
    "notes": ""
  },
  {
    "id": "alias-grace",
    "title": "Alias Grace",
    "author": "Margaret Atwood",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "fiction",
      "literature"
    ],
    "frontImage": "images/alias-grace/front.jpg",
    "backImage": "images/alias-grace/back.jpg",
    "notes": ""
  },
  {
    "id": "flesh",
    "title": "Flesh",
    "author": "David Szalay",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "fiction",
      "contemporary literature"
    ],
    "frontImage": "images/flesh/front.jpg",
    "backImage": "images/flesh/back.jpg",
    "notes": ""
  },
  {
    "id": "conspiracy-nation",
    "title": "Conspiracy Nation",
    "author": "Ariel Bogle and Cam Wilson",
    "condition": "Excellent",
    "available": true,
    "tags": [
      "nonfiction"
    ],
    "frontImage": "images/conspiracy-nation/front.jpg",
    "backImage": "images/conspiracy-nation/back.jpg",
    "notes": ""
  },
  {
    "id": "percy-jackson",
    "title": "Percy Jackson Heroes of Olympus Son of Nepture",
    "author": "Rick Riordan",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/percy-jackson/front.jpg",
    "backImage": "images/percy-jackson/back.jpg",
    "notes": ""
  },
  {
    "id": "percy-jackson-heroes-of-olympus-the-mark-of-athena",
    "title": "Percy Jackson Heroes of Olympus The Mark of Athena",
    "author": "Rick Riordan",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/percy-jackson-heroes-of-olympus-the-mark-of-athena/front.jpg",
    "backImage": "images/percy-jackson-heroes-of-olympus-the-mark-of-athena/back.jpg",
    "notes": ""
  },
  {
    "id": "the-great-hunt-wheel-of-time",
    "title": "The Great Hunt (Wheel of Time)",
    "author": "Robert Jordan",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/the-great-hunt-wheel-of-time/front.jpg",
    "backImage": "images/the-great-hunt-wheel-of-time/back.jpg",
    "notes": ""
  },
  {
    "id": "the-dragon-reborn-the-wheel-of-time",
    "title": "The Dragon Reborn (The Wheel of Time)",
    "author": "Robert Jordan",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "fantasy",
      "fiction"
    ],
    "frontImage": "images/the-dragon-reborn-the-wheel-of-time/front.jpg",
    "backImage": "images/the-dragon-reborn-the-wheel-of-time/back.jpg",
    "notes": ""
  },
  {
    "id": "ivy-bean",
    "title": "Ivy + Bean",
    "author": "Annie Barrows",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/ivy-bean/front.jpg",
    "backImage": "images/ivy-bean/back.jpg",
    "notes": ""
  },
  {
    "id": "ivy-bean-and-the-ghost-that-had-to-go-ivy-bean-2",
    "title": "Ivy + Bean And The Ghost That Had To Go (Ivy + Bean 2)",
    "author": "Annie Burrows",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/ivy-bean-and-the-ghost-that-had-to-go-ivy-bean-2/front.jpg",
    "backImage": "images/ivy-bean-and-the-ghost-that-had-to-go-ivy-bean-2/back.jpg",
    "notes": ""
  },
  {
    "id": "ivy-bean-break-the-fossil-record",
    "title": "Ivy + Bean Break the Fossil Record",
    "author": "Annie Burrows",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "children"
    ],
    "frontImage": "images/ivy-bean-break-the-fossil-record/front.jpg",
    "backImage": "images/ivy-bean-break-the-fossil-record/back.jpg",
    "notes": ""
  },
  {
    "id": "the-red-queen",
    "title": "The Red Queen",
    "author": "Philippa Gregory",
    "condition": "Used",
    "available": true,
    "tags": [
      "historical",
      "fiction"
    ],
    "frontImage": "images/the-red-queen/front.jpg",
    "backImage": "images/the-red-queen/back.jpg",
    "notes": ""
  },
  {
    "id": "what-happens-now",
    "title": "What Happens Now?",
    "author": "Sophia Money-Coutts",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "romance",
      "fiction"
    ],
    "frontImage": "images/what-happens-now/front.jpg",
    "backImage": "images/what-happens-now/back.jpg",
    "notes": ""
  },
  {
    "id": "disquiet-please",
    "title": "Disquiet Please",
    "author": "The New Yorker",
    "condition": "Used - old library book",
    "available": true,
    "tags": [
      "short stories"
    ],
    "frontImage": "images/disquiet-please/front.jpg",
    "backImage": "images/disquiet-please/back.jpg",
    "notes": ""
  },
  {
    "id": "leprechaun-tales",
    "title": "Leprechaun Tales",
    "author": "N/A",
    "condition": "Very Good",
    "available": true,
    "tags": [
      "children",
      "fairytales"
    ],
    "frontImage": "images/leprechaun-tales/front.jpg",
    "backImage": "images/leprechaun-tales/back.jpg",
    "notes": ""
  },
  {
    "id": "irish-fairies",
    "title": "Irish Fairies",
    "author": "Appletree Pocket Guides",
    "condition": "Good - light shelf wear",
    "available": true,
    "tags": [
      "children",
      "fairytales"
    ],
    "frontImage": "images/irish-fairies/front.jpg",
    "backImage": "images/irish-fairies/back.jpg",
    "notes": ""
  },
  {
    "id": "the-outsider",
    "title": "The Outsider",
    "author": "Camus",
    "condition": "Very Good — light shelf wear, no marks inside",
    "available": true,
    "tags": [
      "literature",
      "fiction"
    ],
    "frontImage": "images/the-outsider/front.jpg",
    "backImage": "images/the-outsider/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-philosopher-s-stone-harry-potter-1",
    "title": "Harry Potter and the Philosopher's Stone (Harry Potter 1)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1/front.jpg",
    "backImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-chamber-of-secrets-harry-potter-2",
    "title": "Harry Potter and the Chamber of Secrets (Harry Potter 2)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "children",
      "fantasy"
    ],
    "frontImage": "images/harry-potter-and-the-chamber-of-secrets-harry-potter-2/front.jpg",
    "backImage": "images/harry-potter-and-the-chamber-of-secrets-harry-potter-2/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-prisoner-of-azkaban-harry-potter-3",
    "title": "Harry Potter and the Prisoner of Azkaban (Harry Potter 3)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-prisoner-of-azkaban-harry-potter-3/front.jpg",
    "backImage": "images/harry-potter-and-the-prisoner-of-azkaban-harry-potter-3/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-philosopher-s-stone-harry-potter-1-2",
    "title": "Harry Potter and the Philosopher's Stone (Harry Potter 1)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1-2/front.jpg",
    "backImage": "images/harry-potter-and-the-philosopher-s-stone-harry-potter-1-2/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-goblet-of-fire-harry-potter-4",
    "title": "Harry Potter and the Goblet of Fire (Harry Potter 4)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-goblet-of-fire-harry-potter-4/front.jpg",
    "backImage": "images/harry-potter-and-the-goblet-of-fire-harry-potter-4/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-order-of-the-phoenix-harry-potter-5",
    "title": "Harry Potter and the Order of the Phoenix (Harry Potter 5)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-order-of-the-phoenix-harry-potter-5/front.jpg",
    "backImage": "images/harry-potter-and-the-order-of-the-phoenix-harry-potter-5/back.jpg",
    "notes": ""
  },
  {
    "id": "harry-potter-and-the-half-blood-prince-book-6",
    "title": "Harry Potter and the Half-Blood Prince (Book 6)",
    "author": "J.K. Rowling",
    "condition": "Used",
    "available": true,
    "tags": [
      "fantasy",
      "children"
    ],
    "frontImage": "images/harry-potter-and-the-half-blood-prince-book-6/front.jpg",
    "backImage": "images/harry-potter-and-the-half-blood-prince-book-6/back.jpg",
    "notes": ""
  }
];

window.BOOKS = BOOKS;
